all:
	@clang test_opentimelineio_c.c -O3 -Wall -Werror -I. -lopentimelineio_c -L../../zig-out/lib -o test_opentimelineio_c 
	# @./test_opentimelineio_c || lldb ./test_opentimelineio_c -o run
	@./test_opentimelineio_c

